docs/mysql-plans-and-config.md

Added some clarifying notes to the MySQL plans.

Added a note to the MySQL plans

---

azure-brokerpak/azure-eventhubs.yml
azure-brokerpak/azure-mongodb.yml
azure-brokerpak/azure-mssql-db.yml
azure-brokerpak/azure-mssql-failover.yml
azure-brokerpak/azure-mssql-server.yml
azure-brokerpak/azure-mssql.yml
azure-brokerpak/azure-mysql.yml
azure-brokerpak/azure-redis.yml

Prefixing azure services with csb- to support running maasb broker in parallel with cloud service broker.
#172008596

prefix azure services with csb

---

README.md
azure-brokerpak/azure-eventhubs.yml
docs/azure-event-hubs.md

[#172070733] Added documentation for azure eventhubs service.

documentation for azure eventhubs service

---

azure-brokerpak/azure-mysql.yml
azure-brokerpak/azure-redis.yml
azure-brokerpak/terraform/azure-mysql/provision-mysql.tf
azure-brokerpak/terraform/azure-redis/redis-provision.tf

Implements https://github.com/pivotal/cloud-service-broker/issues/69

Support for specifying minimum TLS version in Azure MySQL and Azure Redis

---

azure-brokerpak/azure-redis.yml
azure-brokerpak/terraform/azure-redis/redis-provision.tf

Implements https://github.com/pivotal/cloud-service-broker/issues/72

Add support for specifying Azure Redis max memory policy

---

docs/configuration.md

Update configuration.md with credhub ref doc
https://github.com/cloudfoundry-incubator/credhub/blob/master/docs/secure-service-credentials.md#service-brokers
See also https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#cloud-foundry-bind-resource-object

Update configuration.md with credhub ref doc

---

README.md

I don't know if there's a better place to point to than here. 🤷

Fix a broken brokerpak development link

---

docs/brokerpak-specification.md

Inlined part of billing.md into broker-pak-specification.md
with help from unit test at https://github.com/pivotal/cloud-service-broker/blob/1fc480f365751eb576a4038b9efa6b55789445ca/utils/utils_test.go#L90-L136

Refine documentation for request.default_labels

---

azure-brokerpak/azure-mysql.yml
azure-brokerpak/terraform/azure-mysql/provision-mysql.tf

Fix creation of Azure MySQL Basic tier due to threat detection policies failing to create even when not enabled.

Add support for Azure MySQL firewall rules.

---

azure-brokerpak/terraform/azure-mssql/bind-mssql.tf

Fixes https://github.com/pivotal/cloud-service-broker/issues/151

Add execute permission during bind for Azure SQL stored procedures

---

cmd/client.go
cmd/pak.go
pkg/brokerpak/cmd.go
pkg/client/example-runner.go
pkg/client/example_logger.go

- this makes it easier to work out which log line relates to which
example
- also logs a summary at the end
[#177317568](https://www.pivotaltracker.com/story/show/177317568)

chore: log concurrent ID when running examples

---

brokerapi/brokers/brokers_test.go
brokerapi/brokers/service_broker.go
cmd/serve.go
go.mod
go.sum
pkg/broker/broker_test.go
pkg/broker/brokerfakes/fake_service_provider.go
pkg/broker/catalog.go
pkg/broker/registry_test.go
pkg/broker/service_definition.go
pkg/broker/service_definition_test.go
pkg/broker/service_provider.go
pkg/client/client.go
pkg/client/example_runner.go
pkg/providers/builtin/base/mixins.go
pkg/providers/tf/definition.go
pkg/providers/tf/definition_test.go
pkg/providers/tf/provider.go
pkg/server/cf_sharing.go
pkg/server/cf_sharing_test.go
pkg/server/fakes/servicebroker.go
utils/correlation/correlation.go
utils/correlation/correlation_test.go
utils/utils.go
utils/utils_test.go

Makes use of new feature to log request ID
[#177648620](https://www.pivotaltracker.com/story/show/177648620)

Update to brokerapi v8

---

brokerapi/brokers/brokers_test.go
brokerapi/brokers/service_broker.go
cmd/serve.go
pkg/broker/broker_test.go
pkg/broker/catalog.go
pkg/broker/registry_test.go
pkg/broker/service_definition.go
pkg/broker/service_definition_test.go
pkg/broker/service_provider.go
pkg/client/client.go
pkg/client/example_runner.go
pkg/providers/builtin/base/mixins.go
pkg/providers/tf/definition.go
pkg/providers/tf/definition_test.go
pkg/providers/tf/provider.go
pkg/server/cf_sharing.go
pkg/server/cf_sharing_test.go
pkg/server/fakes/servicebroker.go
utils/utils.go
utils/utils_test.go

[#177160708](https://www.pivotaltracker.com/story/show/177160708)

chore: stop using deprecated brokerapi types

---

pkg/client/client.go

My proposal to fix the issue #210 Client command should urlencode password

fix for issue #210

---

.github/workflows/test.yml
Makefile

Follows on from https://github.com/cloudfoundry-incubator/cloud-service-broker/commit/1867324f5ba4004ba51337687f9cde7fea543d5a
[#177117499](https://www.pivotaltracker.com/story/show/177117499)

test: use Go 1.16

---

utils/ziputil/zip.go

The brokerpak spec says that a brokerpak is a zip file. This resolves
two issues that caused the unzip command to have errors:
- the unexpected root element ("/") has been removed
- directories now have a trailing slash "/" so that they are correctly extracted as directories, and not as files

fix: brokerpak zip compatibility

---

db_service/models/db.go
db_service/models/db_test.go
integrationtest/database_encryption_test.go
integrationtest/fixtures/brokerpak-with-fake-provider/fake-bind.tf
integrationtest/fixtures/brokerpak-with-fake-provider/fake-provision.tf
integrationtest/fixtures/brokerpak-with-fake-provider/fake-service.tf
integrationtest/fixtures/brokerpak-with-fake-provider/fake-service.yml

[#178797967](https://www.pivotaltracker.com/story/show/178797967)

feat: encrypt binding outputs

---

cmd/tf.go
db_service/models/db.go
db_service/models/db_test.go
integrationtest/database_encryption_test.go
pkg/providers/tf/job_runner.go

[#178987712](https://www.pivotaltracker.com/story/show/178987712)

feat: encrypt terraform workspace

---

integrationtest/database_encryption_test.go
integrationtest/fixtures/brokerpak-for-subsume-cancel/fake-string-provision.tf
integrationtest/fixtures/brokerpak-for-subsume-cancel/fake-string-service.yml
integrationtest/fixtures/brokerpak-for-subsume-cancel/fake-uuid-provision.tf
integrationtest/fixtures/brokerpak-for-subsume-cancel/fake-uuid-service.yml
integrationtest/fixtures/brokerpak-for-subsume-cancel/manifest.yml
integrationtest/integrationtest_suite_test.go
integrationtest/subsume_test.go
pkg/providers/tf/job_runner.go
pkg/providers/tf/wrapper/workspace.go
pkg/providers/tf/wrapper/workspace_test.go

[#179053126](https://www.pivotaltracker.com/story/show/179053126)

feat: subsume should be cancelled when destructive

---

integrationtest/database_encryption_test.go
integrationtest/fixtures/brokerpak-with-fake-provider/fake-provision.tf
integrationtest/fixtures/brokerpak-with-fake-provider/fake-service.yml

Testing encryption on update, unbind and deprovision for both terraform and params data
[#179006636](https://www.pivotaltracker.com/story/show/179006636)

Encryption tests

---

cmd/serve.go
integrationtest/database_encryption_test.go
internal/encryption/compoundencryptor/compoundencryptor.go
internal/encryption/dbrotator/dbrotator.go
internal/encryption/dbrotator/dbrotator_test.go

[#179355271](https://www.pivotaltracker.com/story/show/179355271)

Add tests for key rotation

---

cmd/serve.go
db_service/models/historical_db.go
integrationtest/database_encryption_test.go
internal/encryption/delete_password_metadata.go
internal/encryption/delete_password_metadata_test.go
internal/encryption/parse_configuration.go
internal/encryption/parse_configuration_test.go
internal/encryption/passwordcombiner/combiner.go
internal/encryption/passwordcombiner/combiner_test.go

[#179355270](https://www.pivotaltracker.com/story/show/179355270)

feat: Clean up password metadata that are no longer used

---

cmd/serve.go
docs/configuration.md

[#179622297](https://www.pivotaltracker.com/story/show/179622297)

Add docs for encryption feature

---

pkg/providers/tf/provider_test.go

We saw an intermittent test panic today and it looks like it's because errors are not
checked before a pointer is dereferenced. By reporting the error rather
than panicing we can get closer to diagnosis if it happens again.
[#180419180](https://www.pivotaltracker.com/story/show/180419180)

test: check for errors before dereferencing pointer

---

brokerapi/brokers/brokers_test.go
brokerapi/brokers/service_broker.go

Because we have added a new check to provision and update parameters
it's possible that some workflows that used to pass will now fail. While
the correct action is probably to update the respective brokerpaks,
allowing the check to be turned off give users options to delay those
updates until an appropriate moment.
[#178067889](https://www.pivotaltracker.com/story/show/178067889)

chore: allow disabling of parameters check

---

brokerapi/brokers/brokers_test.go
brokerapi/brokers/service_broker.go

[#181013270](https://www.pivotaltracker.com/story/show/181013270)

Put all provision/update validation behind a feature flag

---

docs/brokerpak-specification.md
docs/draft-release-notes.md
internal/brokerpak/manifest/manifest.go
internal/brokerpak/manifest/parser_test.go
internal/brokerpak/manifest/terraform_upgrade_path.go

[#181061008](https://www.pivotaltracker.com/story/show/181061008)

feat: `terraform_upgrade_path` can be specified and validated

---

pkg/providers/tf/job_runner.go

[#180312162](https://www.pivotaltracker.com/story/show/180312162)
Signed-off-by: James Norman <normanja@vmware.com>

chore: remove unnecessary call to operationFinished

---

brokerapi/broker/broker_test.go
brokerapi/broker/last_binding_operation_test.go
brokerapi/broker/last_instance_operation.go
brokerapi/broker/last_instance_operation_test.go

chore: Transferred last operation tests to ginkgo

---

brokerpaktestframework/test_instance.go

chore: integration test client can update the broker

---

internal/brokerpak/manifest/manifest.go
internal/brokerpak/manifest/parser.go
internal/brokerpak/manifest/parser_test.go

- will be used to replace terraform providers, during renames and upgrade
[#181404983]
Co-Authored-By: Ruben Koster <hi@rkoster.dev>

chore: added terraform_state_provider_replacements to manifest

---

go.mod
go.sum
integrationtest/integrationtest_suite_test.go
tools/tools.go

allows for attaching to broker process started by the integration test
-* [ ] Have you added Draft Release Notes in `docs/draft-release-notes.md`?-

chore: added gops to CSB

---

integrationtest/fixtures/brokerpak-terraform-0.13-with-renamed-provider/fake-service.yml
integrationtest/fixtures/brokerpak-terraform-0.13/fake-service.yml
integrationtest/terraform_rename_provider_test.go
integrationtest/terraform_upgrade_0.12_test.go
pkg/providers/tf/command/terraform_command.go
pkg/providers/tf/command/terraform_command_test.go
pkg/providers/tf/invoker/terraform_012_invoker.go
pkg/providers/tf/invoker/terraform_012_invoker_test.go
pkg/providers/tf/invoker/terraform_default_invoker.go
pkg/providers/tf/invoker/terraform_default_invoker_test.go
pkg/providers/tf/workspace/workspace_test.go

feat: rename provider before deleting instance/binding

---

brokerpaktestframework/test_instance.go

~* [ ] Have you added Draft Release Notes in `docs/draft-release-notes.md`?~
* [x ] Have you followed the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary)?

chore: increase retry max time brokerpak integration test

---

brokerpaktestframework/test_instance.go

- Helpful while debugging, requests dont timeout

chore: removed timeouts for the brokerpak integration tests

---

cmd/serve.go
docs/draft-release-notes.md
integrationtest/helper/client.go
integrationtest/helper/start_broker.go
integrationtest/helper/test_helper.go
integrationtest/info_test.go
internal/infohandler/infohandler.go
internal/infohandler/infohandler_suite_test.go
internal/infohandler/infohandler_test.go

feat: new "/info" endpoint for diagnostics reports version and uptime

---

brokerapi/broker/bind_test.go
brokerapi/broker/deprovision.go
brokerapi/broker/services.go
integrationtest/database_encryption_test.go
integrationtest/update_brokerpak_hcl_test.go
internal/brokerpak/reader/reader.go
pkg/broker/example.go
pkg/broker/registry.go
pkg/broker/service_definition.go
pkg/broker/service_definition_test.go
pkg/broker/service_provider.go
pkg/brokerpak/cmd.go
pkg/brokerpak/cmd_test.go
pkg/brokerpak/config.go
pkg/brokerpak/config_test.go
pkg/brokerpak/registrar.go
pkg/brokerpak/registrar_test.go
pkg/client/broker_response.go
pkg/client/example_runner.go
pkg/client/example_runner_test.go
pkg/generator/types.go
pkg/providers/tf/definition.go
pkg/providers/tf/provider.go
pkg/providers/tf/provider_test.go

Follows on from commit bdd1de9
https://github.com/golang/go/wiki/CodeReviewComments#initialisms
Go guidelines (and statickcheck rule ST1003) recommend using ID, JSON,
etc... rather than Id, Json, etc...

chore: fix some more initialisms

---

integrationtest/upgrade_terraform_before_unbind_test.go

[#182086648](https://www.pivotaltracker.com/story/show/182086648)

test: fix flake with unbind after Terraform upgrade

---

staticcheck.conf

This enables ST1003 to catch pooly chosen identifiers
https://staticcheck.io/docs/checks#ST1003
[#177206960](https://www.pivotaltracker.com/story/show/177206960)

chore: enable staticcheck rule ST1003

---

brokerapi/broker/deprovision.go
brokerapi/broker/provision.go
brokerapi/broker/update.go

- removed usages of brokerService and serviceHelper

chore: refactor, rename local variables to match the type

---

docs/brokerpak-intro.md

fix: solve some wordy errors in brokerpak intro documentation

---

pkg/providers/tf/definition.go

Co-authored-by: Marcela Campo <mcampo@vmware.com>

chore: refactor, removed unused Internal flag on tfdefinition

---

pkg/broker/service_definition.go
pkg/varcontext/builder.go
pkg/varcontext/builder_test.go
pkg/varcontext/interpolation/funcs.go

The variables() function is complex. I tried to understand it for an
investigation, and found that some names and comments had scope for
improvement.
[#182111319](https://www.pivotaltracker.com/story/show/182111319)

chore: improve readability of variables computation

---

pkg/broker/service_provider.go
pkg/providers/tf/bind.go
pkg/providers/tf/outputs.go
pkg/providers/tf/provider.go

[#182112028](https://www.pivotaltracker.com/story/show/182112028)
Co-Authored-By: Jatin Naik <451613+tinygrasshopper@users.noreply.github.com>

chore: refactor - extract Terraform output parsing

---

pkg/providers/tf/deployment_manager.go
pkg/providers/tf/deployment_manager_test.go
pkg/providers/tf/provider.go

test: Add tests for deployment manager

---

brokerpaktestframework/terraform_mock.go
docs/draft-release-notes.md

[#181404871](https://www.pivotaltracker.com/story/show/181404871)

chore: rename brokerpaktestframework.ReturnTFState() to SetTFState()

---

pkg/providers/tf/deprovision.go
pkg/providers/tf/imports.go
pkg/providers/tf/provider.go
pkg/providers/tf/unbind.go
pkg/providers/tf/update_test.go

Co-Authored-By: James Norman <jdnnorman@gmail.com>

chore: Refactor provider layer

---

pkg/providers/tf/tf_suite_test.go
pkg/providers/tf/unbind_test.go

[#182112028](https://www.pivotaltracker.com/story/show/182112028)

test: add provider unbind tests

---

pkg/providers/tf/deprovision_test.go
pkg/providers/tf/tf_suite_test.go

test: add provider deprovision unit tests

---

pkg/providers/tf/imports_test.go

test: Move import test to its own test file

---

pkg/providers/tf/bind.go
pkg/providers/tf/outputs.go
pkg/providers/tf/outputs_test.go

test: add provider output tests

---

pkg/providers/tf/imports_test.go
pkg/providers/tf/poll_instance_test.go

test: add pool instance test

---

dbservice/models/db.go
integrationtest/subsume_test.go
pkg/providers/tf/bind.go
pkg/providers/tf/bind_test.go
pkg/providers/tf/deployment_manager.go
pkg/providers/tf/deployment_manager_test.go
pkg/providers/tf/deprovision.go
pkg/providers/tf/deprovision_test.go
pkg/providers/tf/provider.go
pkg/providers/tf/provision.go
pkg/providers/tf/provision_test.go
pkg/providers/tf/tf_suite_test.go
pkg/providers/tf/tffakes/fake_deployment_manager_interface.go
pkg/providers/tf/unbind.go
pkg/providers/tf/unbind_test.go
pkg/providers/tf/update.go

chore: Clean up last op #180312161

---

brokerpaktestframework/terraform_mock.go

[#182362436](https://www.pivotaltracker.com/story/show/182362436)

test: instantiate tf state when mock TF created

---

brokerpaktestframework/test_instance_builder.go
docs/draft-release-notes.md

feat: extra folders needed for brokerpak build are now supported

---

upgrade-all-plugin/README.md
upgrade-all-plugin/main.go

chore: Edit help text to be similar to CLI style help text

---

Makefile

It's useful to have CSB installed locally, this change:
- adds a make target to install it to /usr/local/bin/csb
- improves the version string so that you can tell which version you
installed

chore: make target for local install

---

docs/services-requirements-checklist.md

docs: Adding Services requirements checklist

---

pkg/broker/variables.go
pkg/broker/variables_test.go

[#182888838](https://www.pivotaltracker.com/story/show/182888838)

feat: Allow setting null for enum properties

---

Dockerfile

[#183463935](https://www.pivotaltracker.com/story/show/183463935)
Signed-off-by: Andrea Zucchini <zandrea@vmware.com>

chore: AWS RDS CA certificate needed for testing

---

.github/workflows/release.yml
.goreleaser.yaml

[#182831564](https://www.pivotaltracker.com/story/show/182831564)

chore: Automate release using GoReleaser

---

.goreleaser.yaml

chore: Make sure dep updates are grouped together

---

.goreleaser.yaml

chore: Update release artefacts name template

---

docs/user-guides/extending-a-service.md

[#183773752](https://www.pivotaltracker.com/story/show/183773752)

chore: add TF test section in docs to extend a service

---

docs/user-guides/developer-experience.md
docs/user-guides/docker.md

chore: new tutorial added explaining steps for local development

---

docs/user-guides/writing-your-first-brokerpak.md

docs: enhance tutorial on writing your first brokerpak

---

brokerapi/broker/last_instance_operation.go

fix: reword message error

---

docs/brokerpak-specification.md
docs/configuration.md
docs/terraform-upgrades.md

[#184150171](https://www.pivotaltracker.com/story/show/184150171)

docs: document upgrade configuration and process

---

docs/terraform-upgrades.md

Make it clearer that feature flags and Brokerpak specification changes are needed to enable upgrades

docs: Update terraform-upgrades.md

---

README.md
TESTING.md
docs/README.md
docs/brokerpak-dissection.md
docs/brokerpak-specification.md

* ~[ ] Have you added or updated tests to validate the changed functionality?~
* ~[ ] Have you added Release Notes in the docs repositories?~

docs: Fix broken links

---

.github/workflows/md-link-check.yml
.github/workflows/mlc-config.json
README.md

* ~[ ] Have you added or updated tests to validate the changed functionality?~
* ~[ ] Have you added Release Notes in the docs repositories?~

chore: Automatically validate documentation links

---

docs/terraform-upgrades.md

Updated the example code and added note

docs: Update Terraform Upgrades docs

---

cmd/purge.go

A confirmation message when the operation has been successful improves the user experience.

chore: add log message when deleting service

---

README.md
brokerapi/broker/services.go
cmd/local.go
docs/README.md
internal/local/catalog.go
internal/local/upgrade_service.go
pkg/featureflags/feature_flags.go
pkg/providers/tf/invoker/terraform_invoker_factory.go
pkg/providers/tf/invoker/terraform_invoker_factory_test.go

chore: skip provider rename logic is now behind a feature flag

---

.github/dependabot.yml

[#184943945](https://www.pivotaltracker.com/story/show/184943945)

chore: update dependabot.yml to ignore broken version of sqlite driver

---

.goreleaser.yaml

[#184978710](https://www.pivotaltracker.com/story/show/184978710)

chore: add version to released binary

---

pkg/brokerpak/examples/manifest.yml

* ~[ ] Have you added or updated tests to validate the changed functionality?~
* ~[ ] Have you added Release Notes in the docs repositories?~

chore: Bump artefacts used in `pak init` manifest

---

cmd/local.go
internal/local/service.go

[##182651749](https://www.pivotaltracker.com/story/show/182651749)

chore: add service csb command

---

README.md
internal/local/update_service.go

chore(csb): csb update command supports upgrades enabled

---

cmd/client.go
pkg/client/client.go

Added a development support command `client upgrade` for testing the upgrade flow
* [~] Have you added or updated tests to validate the changed functionality?
* [~] Have you added Release Notes in the docs repositories?

feat: csb client upgrade sub-command

---

integrationtest/fixtures/global-labels/manifest.yml
integrationtest/fixtures/maintenance-info/fake-provision.tf
integrationtest/fixtures/maintenance-info/manifest.yml
integrationtest/fixtures/osbapi/manifest.yml
integrationtest/fixtures/prevent-destroy-during-update/manifest.yml
integrationtest/fixtures/terraform-0.12/manifest.yml
integrationtest/fixtures/terraform-0.13/fake-provision.tf
integrationtest/fixtures/terraform-0.13/manifest.yml
integrationtest/fixtures/terraform-block-action-before-upgrade-updated/fake-provision.tf
integrationtest/fixtures/terraform-block-action-before-upgrade-updated/manifest.yml
integrationtest/fixtures/terraform-block-action-before-upgrade/manifest.yml
integrationtest/fixtures/terraform-module-upgrade-updated/fake-provision.tf
integrationtest/fixtures/terraform-module-upgrade-updated/manifest.yml
integrationtest/fixtures/terraform-module-upgrade/manifest.yml
integrationtest/fixtures/terraform-upgrade-updated/fake-bind.tf
integrationtest/fixtures/terraform-upgrade-updated/fake-provision.tf
integrationtest/fixtures/terraform-upgrade-updated/manifest.yml
integrationtest/fixtures/terraform-upgrade/manifest.yml
integrationtest/fixtures/tf_attribute_skip/fake-provision.tf
integrationtest/fixtures/tf_attribute_skip/manifest.yml

[#184640225](https://www.pivotaltracker.com/story/show/184640225)

chore: update version of random provider used in integration tests

---

Dockerfile

[#186660285](https://www.pivotaltracker.com/story/show/186660285)

chore: pin Dockerfile Alpine version again

---

Dockerfile

[#186660285](https://www.pivotaltracker.com/story/show/186660285)
Use workaround described in:
https://github.com/mattn/go-sqlite3/issues/1164#issuecomment-1848677118

chore: workaround go-sqlite3 alpine3.19 issue

---

.github/workflows/codeql.yml

Related Issues:
- https://github.com/github/codeql/issues/13992

chore: update codeql-action to support new go toolchains

---

go.mod
go.sum

Vulnerability Report: https://pkg.go.dev/vuln/GO-2024-2611
[#187061621](https://www.pivotaltracker.com/story/show/187061621)

fix: CVE-2024-24786 found

---

internal/brokerpak/manifest/terraform_resource.go

[#187199931](https://www.pivotaltracker.com/story/show/187199931)

chore: clarify url_template logic after v1.0.0 changes to core

---

docs/user-guides/writing-your-first-brokerpak.md

[#187200917](https://www.pivotaltracker.com/story/show/187200917)

docs: update writing your first brokerpak tutorial

---

docs/brokerpak-dissection.md
docs/brokerpak-specification.md
docs/terraform-upgrades.md
docs/user-guides/developer-experience.md

docs: Make more terraform to opentofu replacements

---

integrationtest/terraform_upgrade_test.go
pkg/providers/tf/executor/executor.go

[#187379198](https://www.pivotaltracker.com/story/show/187379198)

chore: change more instances of terraform to tofu

---

brokerapi/broker/update.go
brokerapi/broker/update_test.go
integrationtest/maintenance_info_test.go
integrationtest/subsume_test.go
integrationtest/terraform_block_action_before_upgrade_test.go
integrationtest/terraform_module_upgrade_test.go
integrationtest/terraform_rename_provider_test.go
integrationtest/terraform_upgrade_test.go
internal/brokerpak/manifest/parser.go
internal/brokerpak/manifest/parser_test.go
pkg/brokerpak/registrar.go
pkg/providers/tf/bind_test.go
pkg/providers/tf/deployment_manager.go
pkg/providers/tf/deployment_manager_test.go
pkg/providers/tf/provider.go
pkg/providers/tf/provision.go
pkg/providers/tf/provision_test.go
pkg/providers/tf/terraform_plan_output_matcher.go
pkg/providers/tf/terraform_plan_output_matcher_test.go
pkg/providers/tf/terraform_upgrade_checker.go
pkg/providers/tf/terraform_upgrade_checker_test.go
pkg/providers/tf/unbind_test.go
pkg/providers/tf/update_test.go
pkg/providers/tf/upgrade.go
pkg/providers/tf/upgrade_test.go

chore: rename tf to tofu

---

dbservice/dbservice_suite_test.go
dbservice/migrations_test.go
dbservice/recover_in_progress_operations_test.go
dbservice/vcap_test.go

Requested in PR comment for https://github.com/cloudfoundry/cloud-service-broker/pull/983
[#187331719](https://www.pivotaltracker.com/story/show/187331719)

test: move "dbservices" tests to Ginkgo style

---

README.md
docs/brokerpak-specification.md
docs/opentofu_migration_guide.md

[#187199940](https://www.pivotaltracker.com/story/show/187199940)

docs: opentofu migration guide

---

Makefile

fix: Broker version should be correctly set as v2.0.0

---

.github/workflows/release.yml

chore: Update goreleaser command to work with latest version

---

.github/workflows/manual-releaser.yml

chore: create manual-releaser action

---

.github/workflows/manual-releaser.yml

chore: Update manual-releaser.yml

---

.github/workflows/manual-releaser.yml

chore: Use tag to release

---

.goreleaser.yaml

chore: update version flag in go releases

---

internal/brokercredstore/brokercredstore_suite_test.go
internal/brokercredstore/credhub_test.go

- Adds tests based on current implementation
- Will allow refactoring of current implementation

test: add CredHub API testing

---

internal/brokerchapi/brokerchapi_suite_test.go
internal/brokerchapi/brokerchapi_test.go
internal/brokerchapi/generateFakeCerts.sh

Makes sure that the `InsecureSkipTLSVerify` and `CACert` properties do what they are supposed to.

test: CredHub CA Cert and TLS skip

---

internal/credhubrepo/credhub_repo.go
internal/credhubrepo/credhub_repo_test.go

In the unlikely event that two Bind operations happen at the same time, we would need to make two calls to CredHub to store the binding, but we should only make one call to UAA to get a CredHub token.

fix: handle concurrent attempts to fetch token

---

.github/workflows/dependabot-test.yml

chore: fix approve step in github action (#1284)

chore: attempt to autoapprove PRs from dependabot (#1283)
