- Makefile
When you `USE_GO_CONTAINERS=true make build`, the resulting `build/cloud-service-broker.linux` wants the particular version of GLIBC that present at build-time in the Go container to be present at run-time. This means the resulting binary won't properly run in either Alpine or Ubuntu docker images. 
(Instead you'll see cryptic messages in Alpine about the file not being found when you run the binary even though _it's obviously right there_. I spent a couple hours trying to figure out why I couldn't `make run-broker-aws-docker` before I finally tried it with an Ubuntu image and saw more info about GLIBC_2_28 files not being present and figured out what was up.)
This change passes the `CGO_ENABLED` env var to the Go Docker image (it was ignored previously) to ensure a static binary is …
> Make fully-static Go binary to work with Alpine, Ubuntu, etc.

- docs/brokerpak-specification.md
The parameter, per code in existing brokerpaks, is called `template_ref` rather than `template_uri`.
> Make documented parameter name match implementation

- azure-brokerpak/azure-mssql-db-failover.yml
- azure-brokerpak/azure-mssql-db.yml
- azure-brokerpak/manifest.yml
- azure-brokerpak/terraform/azure-cosmosdb/provision-cosmosdb-sql.tf
- azure-brokerpak/terraform/azure-eventhubs/azure-eventhubs-bind.tf
- azure-brokerpak/terraform/azure-eventhubs/azure-eventhubs.tf
- azure-brokerpak/terraform/azure-mongodb/azure-mongodb.tf
- azure-brokerpak/terraform/azure-mssql-db-failover/provision-fog-db.tf
- azure-brokerpak/terraform/azure-mssql-db/provision-mssql-db.tf
- azure-brokerpak/terraform/azure-mssql-failover/provision-mssql-failover.tf
- azure-brokerpak/terraform/azure-mssql-server/mssql-server-provision.tf
- azure-brokerpak/terraform/azure-mssql/provision-mssql.tf
- azure-brokerpak/terraform/azure-mysql/provision-mysql.tf
- azure-brokerpak/terraform/azure-postgres/postgres-provision.tf
- azure-brokerpak/terraform/azure-redis/redis-provision.tf
- azure-brokerpak/terraform/azure-resource-group/resource-group-provision.tf
- azure-brokerpak/terraform/azure-storage/account-provision.tf
- azure-brokerpak/terraform/subsume-masb-mssql-db/azure-provider.tf
- azure-brokerpak/terraform/subsume-mssql-db/azure-provider.tf
Implements: https://github.com/pivotal/cloud-service-broker/issues/100
Upgrades to Azure RM provider version 2.31.0, and switches from azurerm_sql_database to newer azurerm_mssql_database resource type which is required to support the new short_term_retention_policy configuration block.
> Add support for Azure SQL short term retention period.

- azure-brokerpak/azure-mysql.yml
- azure-brokerpak/azure-redis.yml
- azure-brokerpak/terraform/azure-mysql/provision-mysql.tf
- azure-brokerpak/terraform/azure-redis/redis-provision.tf
Move TLS configuration from user_inputs to plan_inputs for Azure MySQL and Azure Redis.
Add support for controlling backup retention for Azure MySQL.
Add support for firewall rules for Azure Redis.
> Move TLS config to plan_inputs, MySQL backup retention, Redis firewall rules.

- Makefile
The Dockerfile already builds the binary that it needs. Removing this dependency enables building the Docker image by itself.
> Remove unneeded dependency

- db_service/migrations.go
- db_service/models/db.go
- db_service/models/historical_db.go
Expands the size of the Workspace column to handle deployments where the Terraform workspace is greater than 64K. 
We need this for our eks-brokerpak since the `.tfstate` ends up about 196K...!
Mediumtext allows for workspaces up to 16384K.
> Enlarge DB column to allow for larger Terraform state

- docs/brokerpak-dissection.md
- docs/brokerpak-specification.md
- docs/configuration.md
- docs/installation.md
This PR makes explicit how to use feature flags, in particular to turn on serving Json Schema into catalog (relates to #166)
I also noticed that `csb generate customize` generates HTML documentation including feature flags, but this file is not visible on github. I'm not sure whether/how to mention presence of this `csb generate customize` and whether some other documentation element describe it.
> Document use of feature flags including enable-catalog-schemas

- db_service/migrations.go
- db_service/models/historical_db.go
This PR fixes a problem with my previous fix for a problem where old DBs aren't handling larger Terraform workspace state. [Here's the description of the problem with my previous fix for the problem](https://github.com/cloudfoundry-incubator/cloud-service-broker/pull/168#issuecomment-768519993). 😳 🤦 😞 
Once merged this should probably be tagged v0.2.3 ASAP to minimize the set of people who will end up with a stray/unused DB table as a result of deploying my previous PR in 0.2.2. (It's relatively harmless, but even so, sorry about that.)
Tagging @erniebilling as he's likely best equipped to evaluate and merge.
> Fix problem with TerraformDeploymentV2 migration

- brokerapi/brokers/brokers_test.go
- brokerapi/brokers/service_broker.go
- docs/brokerpak-specification.md
- pkg/broker/broker_test.go
- pkg/broker/service_definition.go
- pkg/providers/builtin/storage/definition.go
- utils/request/request_parser.go
- utils/request/request_parser_test.go
[#177115261](https://www.pivotaltracker.com/story/show/177115261)
Implements https://github.com/cloudfoundry-incubator/cloud-service-broker/issues/138
> Expose context and x_broker_api_originating_identity to brokerpaks

- pkg/broker/service_provider.go
- pkg/credstore/credstore.go
- pkg/providers/builtin/base/broker_base.go
- pkg/server/cf_sharing.go
- since upating to counterfeiter 6.4.1 there has been a warning to
update to use counterfeiter directives
- this change resolves that warning by introducing counterfeiter
directives
- the generated code has not changed
https://github.com/maxbrunsfeld/counterfeiter#step-2b---add-counterfeitergenerate-directives
[#177622925](https://www.pivotaltracker.com/story/show/177622925)
> chore: use counterfeiter directives

- brokerapi/brokers/service_broker.go
- cmd/client.go
- pkg/client/client.go
- pkg/client/example_runner.go
- pkg/providers/tf/provider.go
- utils/correlation/correlation.go
- utils/correlation/correlation_suite_test.go
- utils/correlation/correlation_test.go
Each HTTP request from the examples now sends a unique value in the
'X-Correlation-ID' header and also logs the value so that each request
from the example test runner can in principle be correlated with events
in the broker logs.
The work to add request ID logging to all broker logs will be done in
[#177289977](https://www.pivotaltracker.com/story/show/177289977) but as
a proof of concept, a couple of logging statements in the Provision
request were updated so that they would log the correlation ID.
[#177317568](https://www.pivotaltracker.com/story/show/177317568)
> chore: examples should send unique ID in each request

- brokerapi/brokers/service_broker.go
- pkg/brokerpak/registrar_test.go
- pkg/providers/builtin/account_managers/service_account_manager.go
- pkg/providers/tf/job_runner.go
- pkg/providers/tf/provider.go
- pkg/providers/tf/wrapper/workspace.go
- pkg/providers/tf/wrapper/workspace_test.go
log lines relating to a request should show the correlation ID so that
they can be differentiated when there are concurrent requests
[#177289977](https://www.pivotaltracker.com/story/show/177289977)
> chore: broker logs should show correlation ID

- pkg/providers/builtin/account_managers/service_account_manager.go
- staticcheck.conf
Since #225 these are the remaining deprecated API calls which should be
updated so that staticheck rule SA1019 can be activated. It should be
noted that #226 seeks to remove this file, but as #226 cannot be merged
just yet, we might as well move forwards with activating the staticcheck
rule.
[#177160708](https://www.pivotaltracker.com/story/show/177160708)
> chore: remove deprecated API calls

- brokerapi/brokers/brokers_test.go
- db_service/models/db.go
- db_service/models/db_test.go
- db_service/models/fakes/fake_encryption.go
- internal/encryption/encryption.go
restrictions
MySQL's utf8 permits only the Unicode characters that can be represented
with 3 bytes in UTF-8, Changing the encoding in the dabatase fixes it,
but it requires migrations and it is also database dependent.
Encoding to b64 makes it more straightforward.
[#178795926](https://www.pivotaltracker.com/story/show/178795926)
> encryption: encode before saving to database to avoid mysql encoding

- pkg/providers/tf/wrapper/workspace.go
When a subsume is cancelled because it would be destructive, the output
from `terraform plan` should be logged.
[#178943997](https://www.pivotaltracker.com/story/show/178943997)
> feat: cancelled subsume should log reason

- internal/encryption/parser/parser.go
- internal/encryption/parser/parser_suite_test.go
- internal/encryption/parser/parser_test.go
- pkg/broker/catalog.go
- pkg/broker/registry.go
- pkg/broker/service_definition.go
- pkg/providers/tf/definition.go
- pkg/validation/field_error.go
- pkg/validation/field_error_test.go
- pkg/validation/struct_validator.go
- pkg/validation/struct_validator_test.go
In future we plan to accept multiple encryption passwords with format:
```json
[
{
"label": "my-label",
"primary": true,
"password": {
"secret": "fake-super-secret-password"
}
},
{...}
]
```
The format is based on the output of the tile configuration
Based on PR #288 by @FelisiaM
> Validations for new password style

- Makefile
- go.sum
- integrationtest/brokerpaks_test.go
- integrationtest/catalog_test.go
- integrationtest/database_encryption_test.go
- integrationtest/integrationtest_suite_test.go
- integrationtest/subsume_test.go
- tools/tools.go
Integration tests benefit from being run in parallel, and because they
are Ginkgo style tests, need to be run by the ginkgo command to run in
parallel. For now we can run the other tests with `go test` as this
represents less change. The testing times are quite varaible, but this
appears to speed up the overall time for `make test`.
[#179324852](https://www.pivotaltracker.com/story/show/179324852)
> chore: separate unit and integration tests

- db_service/dao.go
- db_service/dao_generator.go
- pkg/providers/tf/job_runner.go
Looks like the newer Gorm is noisier about bad usage such as using a
SELECT to get a record count. These changes fix the warnings that were
printed out during some integration tests.
[#177268286](https://www.pivotaltracker.com/story/show/177268286)
> chore: fix some warnings from updated Gorm

- db_service/migrations.go
- db_service/models/db.go
- db_service/models/historical_db.go
Terraform workspace field used to be a `mediumtext` and then moved to `blob`. The size of the `blob is smaller than `mediumtext` resulting in failures during migration.
[#180161941](https://www.pivotaltracker.com/story/show/180161941)
closes #320
> Change `blob` to `mediumblob` for terraform.workspace

- db_service/migrations.go
- db_service/models/db.go
- db_service/models/historical_db.go
Keeping step 13 as it was would have still failed for cases when the DB already had large workspaces stored (bigger than 64K). We still need the migration id, but it should not run any migration, instead step 14 will make sure the blob size is increased.
[#180161941](https://www.pivotaltracker.com/story/show/180161941)
closes #320
> Edit migrations make sure they succeed

- manifest.yml
Looks like we missed this in 5e194ab
> chore: update cf manifest to Go 1.17

- brokerapi/brokers/brokers_test.go
- brokerapi/brokers/service_broker.go
- integrationtest/database_encryption_test.go
- integrationtest/fixtures/brokerpak-for-multiple-updates/fake-bind.tf
- integrationtest/fixtures/brokerpak-for-multiple-updates/fake-provision.tf
- integrationtest/fixtures/brokerpak-for-multiple-updates/fake-service.yml
- integrationtest/fixtures/brokerpak-for-multiple-updates/manifest.yml
- integrationtest/multiple_update_test.go
- pkg/broker/broker_test.go
- pkg/broker/service_definition.go
- pkg/varcontext/builder_test.go
Stores the merged previous and provided user parameters so that on
subsequent updates, they do not need to be provided again.
For example:
provision: {"foo":"bar","baz":"quz"}
update 1: {"foo":"dax"} -> {"foo":"dax","baz":"quz"}
update 2 before fix: {"baz":"box"} -> {"foo":"bar","bax":"box"}
update 2 after fix:  {"baz":"box"} -> {"foo":"dax","bax":"box"}
[#178213626](https://www.pivotaltracker.com/story/show/178213626)
> fix: persist parameters through multiple updates

- integrationtest/brokerpak_update_test.go
- integrationtest/brokerpaks_test.go
- integrationtest/catalog_test.go
- integrationtest/database_encryption_test.go
- integrationtest/multiple_update_test.go
- integrationtest/subsume_test.go
- integrationtest/terraform_0.12_test.go
- integrationtest/terraform_0.13_test.go
- internal/zippy/archive_test.go
- internal/zippy/extract_test.go
The advantage of the Ginkgo helper is that errors are automatically
checked and the directory is automatically cleaned up.
> test: use Ginkgo TempDir() rather than os.MkdirTemp()

- cmd/serve.go
- internal/brokerpak/packer/pack.go
- pkg/brokerpak/registrar.go
- utils/version.go
This allows someone to:
- make sure they are running with the version they think they are
running with
- help debug any issues by being able to identify the version in use
[#177837115](https://www.pivotaltracker.com/story/show/177837115)
> chore: expose broker and brokerpak versions in logs

- docs/draft-release-notes.md
- pkg/broker/registry.go
- pkg/broker/registry_test.go
- pkg/broker/service_definition.go
If a service has no plans defined in the brokerpak or via environment
variables, then the "cf create-service-broker" command will fail.
This change makes the broker fail on startup if there are no plans, so
that a user gets faster feedback, and also some hints on how to resolve
the problem.
[#180992066](https://www.pivotaltracker.com/story/show/180992066)
> fix: error when a service has no plans

- db_service/setup_db.go
- docs/draft-release-notes.md
Previously the DB connection timeout was not specified, which had the
effect of the app suspending if the database connection could not be
made without any useful error message.
> fix: timeout when cannot connect to state database

- docs/brokerpak-specification.md
Picked up by @mogul during review of #378. Recent [testing on GCP](https://github.com/cloudfoundry/csb-brokerpak-gcp/commit/0828a7a6403578abb40c6ef8642c4fc32680a29b) has shown that the latest Terraform (v1.1) works, so we should update the version statement accordingly.
* ~~[ ] Have you added Draft Release Notes in `docs/draft-release-notes.md`?~~ N/A
> docs: update statement on Terraform versions

- brokerpaktestframework/test_instance_builder.go
[#181249649]
Copy files rather than symlink, to make tests portable in situations in which symlinking to tmp is not allowed
> chore: copy files rather than symlink files in test

- pkg/providers/tf/workspace_updater_test.go
This test is very closely coupled making other refactoring harder.
Specifically it requires a real DB and uses an executor, both of which
are no longer needed as we can make better fakes and simplify the test.
[#181061009](https://www.pivotaltracker.com/story/show/181061009)
Co-authored-by: George Blue <gblue@pivotal.io>
* ~~[ ] Have you added Draft Release Notes in `docs/draft-release-notes.md`?~~ N/A
> chore: refactor brokerpak updates test

- cmd/pak.go
- internal/brokerpak/packer/cache.go
- internal/brokerpak/packer/pack.go
- internal/brokerpak/reader/reader_test.go
- pkg/brokerpak/cmd.go
- pkg/brokerpak/cmd_test.go
added caching which can be turned on by setting an enviornment variable on local
to speedup your local dev loops while running pak
[#181404983]
Signed-off-by: James Norman <normanja@vmware.com>
> chore: speedup pak command in tests

- internal/storage/bind_request_details.go
- internal/storage/bind_request_details_test.go
- internal/storage/encode.go
- internal/storage/provision_request_details.go
- internal/storage/provision_request_details_test.go
- internal/storage/service_binding_credentials.go
- internal/storage/service_binding_credentials_test.go
- internal/storage/service_instance_details.go
- internal/storage/service_instance_details_test.go
- internal/storage/terraform_deployment.go
- internal/storage/terraform_deployments_test.go
- now logs the object ID when decoding fails
- when parsing empty string as JSON, returns empty object rather than
failing
[#181481018](https://www.pivotaltracker.com/story/show/181481018)
> chore: better error handling in storage layer

- .gitignore
- Makefile
[#181404975]
Following up from https://github.com/cloudfoundry/cloud-service-broker/pull/413
Signed-off-by: James Norman <normanja@vmware.com>
> chore: add integration with cache task

- internal/storage/update_all_records.go
- internal/storage/update_all_records_test.go
When encrypting the database, we currently parse and then marshal certain JSON fields.
This is not a required step as we can just decrtypt the previous data as
bytes and then re-encrypt.
[#181481018](https://www.pivotaltracker.com/story/show/181481018)
> chore: don't parse JSON when encrypting

- cmd/serve.go
- docs/draft-release-notes.md
- integrationtest/database_encryption_test.go
- internal/storage/check_all_records.go
- internal/storage/check_all_records_test.go
- internal/storage/update_all_records.go
If there is a problem with reading any field in the database, then we
should fail fast before attempting to encrypt the database, so that we
reduce the change of the database ending up in a partially encrypted
state.
If there is a problem with reading any field in the database, then we
should not attempt to remove any password metadata as it's possible that
the reason the database cannot be read is due to a password having been
removed, and we want to keep the value of any salt so that an encryption
key can still be make.
These checks do access every row in the database. We believe that
databases are small (1000 rows or fewer per table) so this should be
fast, but we would need to revisit if we discovered a customer who is
running at a large enough scale for this to cause performance …
> fix: check readability of database before encryption actions

- docs/draft-release-notes.md
- pkg/broker/registry.go
- pkg/broker/registry_test.go
This changed `beta` tagged services to be disabled by default.
[#181267511](https://www.pivotaltracker.com/story/show/181267511)
> feat: beta services disabled by default

- brokerapi/broker/bind.go
- brokerapi/broker/brokerfakes/fake_storage.go
- brokerapi/broker/storage.go
- brokerapi/broker/unbind.go
- internal/paramparser/parse_bind_details.go
- internal/paramparser/parse_bind_details_test.go
- internal/paramparser/parse_update_details_test.go
- internal/storage/bind_request_details.go
- internal/storage/bind_request_details_test.go
- internal/storage/check_all_records.go
- internal/storage/check_all_records_test.go
- pkg/broker/broker_test.go
- pkg/broker/service_definition.go
Bind request details should always be JSON. We should therefore
parse them as JSON as soon as we can to validate them, as failing fast
makes it easier to trace errors. This means that storage layer should
parse when reading from the database, and parsing should also occur as
soon as possible when handling data in brokeapi.
[#181522793](https://www.pivotaltracker.com/story/show/181522793)
> chore: parse bind request details in storage layer

- pkg/providers/tf/workspace/workspace.go
The struct for parsing the version doesn't need package scope
> chore: clean up TF version parsing

- internal/storage/check_all_records.go
- internal/storage/check_all_records_test.go
- internal/storage/terraform_deployments_test.go
- internal/storage/update_all_records_test.go
This checks that the Terraform workspace can be parsed from JSON.
At the moment, the workspace is parsed again into a struct{} later. There
is a potential further refactor where the workspace is not parsed again,
but it's much more complex than doing this change, and we hope to make
that improvement later.
[#181522793](https://www.pivotaltracker.com/story/show/181522793)
> chore: check terraform workspace parse in storage layer

- internal/storage/bind_request_details_test.go
- internal/storage/provision_request_details_test.go
- internal/storage/service_binding_credentials_test.go
- internal/storage/service_instance_details_test.go
There are some JSON parsing edge cases where we know that we want the
result to be an empty map, but sometimes the JSON parser can fail by
default (to be safer), so we should test that we handle those edge
cases.
[#181522793](https://www.pivotaltracker.com/story/show/181522793)
> chore: improve testing of JSON parsing from database

- db_service/setup_db.go
- docs/draft-release-notes.md
We recently had to debug a situation where setting up the DB connection
failed. We found this difficult because the logs were quite sparse in
what they recorded. This change adds username and TLS string to the log,
both of which should not contain secrets.
> fix: log more details when setting up DB connection

- brokerpaktestframework/test_instance_builder.go
- speeds up the tests while not downloading the depdencies again
> test: remove terraform providers from manifest for brokerpak integration tests

- brokerpaktestframework/terraform_mock.go
- brokerpaktestframework/test_instance.go
- brokerpaktestframework/test_instance_builder.go
- internal/brokerpak/reader/reader.go
New code should not use ioutil as its on the path to deprecation
> chore: don't use ioutil package

- cmd/tf.go
- docs/draft-release-notes.md
- pkg/brokerpak/config.go
- pkg/providers/tf/workspace/additional_state_test.go
- pkg/providers/tf/workspace/workspace.go
- pkg/providers/tf/workspace/workspace_suite_test.go
- pkg/providers/tf/workspace_updater.go
- pkg/providers/tf/workspace_updater_test.go
To support TLS for GCP PostgreSQL, it proved necessary to write
*.pem files for the Terraform provider to use to connect as a client.
This feature is experimental and will change, as the files that are
stored alongside the Terraform state should be configurable.
[#181059797](https://www.pivotaltracker.com/story/show/181059797)
> feat(experimental): store *.pem files alongside Terraform state

- integrationtest/database_encryption_test.go
- integrationtest/terraform_rename_provider_test.go
- integrationtest/terraform_upgrade_0.12_test.go
- integrationtest/terraform_upgrade_test.go
- integrationtest/update_brokerpak_hcl_test.go
- integrationtest/upgrade_terraform_before_delete_test.go
- integrationtest/upgrade_terraform_before_unbind_test.go
[#182117290](https://www.pivotaltracker.com/story/show/182117290)
There were some test flakes in some tests where the broker was stopped an re-started. A theory was that the broker had not completely terminated before the next broker was started and the aliveness test was run, so the aliveness test detected the broker that was shutting down rather than the one that was starting up.
> test: fix flake after termination service broker instance

- brokerpaktestframework/test_instance.go
- docs/draft-release-notes.md
Go is opinionated as to initialisms: https://github.com/golang/go/wiki/CodeReviewComments#initialisms
An API should therefore comply with this pseudo-standard
The original BrokerUrl() method still works, but BrokerURL() is
preferred
> fix(brokerpaktestframework): rename BrokerUrl to BrokerURL

- pkg/providers/tf/job_runner.go
- pkg/providers/tf/provider.go
- pkg/providers/tf/tffakes/fake_job_runner.go
- StageJob was confusing as it is not a Job and it was only used on
create
- moved as a private method on provider and renamed for clarity
[#182112028](https://www.pivotaltracker.com/story/show/182112028)
Co-authored-by: Marcela Campo <mcampo@pivotal.io>
> chore: move stageJob into provider

- docs/draft-release-notes.md
- internal/storage/check_all_records.go
- internal/storage/check_all_records_test.go
- internal/storage/terraform_deployment.go
After commit 7542d45 we are able to add more checking to the loading of
deployments from the database at start up. This follows on from commit
76718c026f99702ba710f5717c4a855d1b8825bb, and means that we fail fast
if there is a corrupt entry in the database.
[#182112028](https://www.pivotaltracker.com/story/show/182112028)
> fix: check readability of deployment workspaces before encryption

- docs/brokerpak-specification.md
- docs/draft-release-notes.md
- integrationtest/fixtures/prevent-destroy-during-update/fake-provision.tf
- integrationtest/fixtures/prevent-destroy-during-update/fake-service.yml
- integrationtest/fixtures/prevent-destroy-during-update/manifest.yml
- integrationtest/fixtures/update-brokerpak-hcl-updated/fake-provision.tf
- integrationtest/prevent_destroy_during_update_test.go
- integrationtest/update_brokerpak_hcl_test.go
- pkg/providers/tf/provider.go
- pkg/providers/tf/workspace/prevent_destroy.go
- pkg/providers/tf/workspace/prevent_destroy_test.go
The lifecycle meta-argument `prevent_destroy` prevents Terraform from
accidentally deleting resources. This can now be added in Terraform
definitions to prevent resource from being deleted during an update.
During the delete process, the value is set to `false` so that service
instances can be successfully deleted.
[#181445529](https://www.pivotaltracker.com/story/show/181445529)
> feat: allow lifecycle.prevent_destroy in HCL

- brokerpaktestframework/terraform_mock.go
- pkg/providers/tf/workspace/tfstate.go
- terraform version from is used when binding to decide if an upgrade is
needed
- This adds that field to the struct where we parse the state and makes
it configurable in the mock terraform so it can be set up differently
for each brokerpak
- This is the simplest implementation. It is worth reviewing when we start testing upgrades in the brokerpaks.
[#182307860](https://www.pivotaltracker.com/story/show/182307860)
> chore: Add tf version to mock terraform and tfState

- cmd/tf.go
- internal/storage/terraform_deployment.go
- internal/storage/terraform_deployments_test.go
- internal/storage/update_all_records_test.go
The "cloud-service-broker tf list" command can be used to print a list
of all the Terraform deployments. This adds a new column for to add the
Terraform state version, so it's possible to see what version each
deployment is at. This is expected to be used for debugging purposes.
> feat: "tf list" subcommand should print state version

- docs/draft-release-notes.md
- pkg/providers/tf/executor/executor.go
> fix: concatenation of words in Terraform error messages

- pkg/providers/tf/deployment_manager.go
- pkg/providers/tf/executor/executor.go
In the previous commit, a fix was made to stop concatenating words in
error messages. This occurred because the newline was previously being
removed, and this was changed to replace it with a space. But sometimes
there is a leading newline or a newline following a space. In these
cases error messages now appear to have double spaces in them which
looks as bad as concatenation, and also causes error message tests to
fail. This commit is aimed at fixing this formatting issues so that
multi-line strings should be converted to normal looking single lines.
> fix: double spaced error messages

- docs/draft-release-notes.md
- integrationtest/fixtures/terraform-module-upgrade-updated/fake-provision.tf
- integrationtest/fixtures/terraform-module-upgrade-updated/fake-service.yml
- integrationtest/fixtures/terraform-module-upgrade-updated/manifest.yml
- integrationtest/fixtures/terraform-module-upgrade/fake-provision.tf
- integrationtest/fixtures/terraform-module-upgrade/fake-service.yml
- integrationtest/fixtures/terraform-module-upgrade/manifest.yml
- integrationtest/terraform_module_upgrade_test.go
- pkg/providers/tf/workspace/instance.go
- pkg/providers/tf/workspace/instance_test.go
Terraform modules are a feature in Terraform. Most of our work
on the Terraform upgrade path has specified Terraform via `template_refs`
which results in not using Terraform modules. However if Terraform is
specified via `template_ref` then a single Terraform module is created.
The outputs from this module used not to be marked as "sensitive" which
meant that Terraform would fail if an output referred to a sensitive
value, which meant that we could not upgrade past Terraform 0.14. This
commit marks all the module outputs as sensitive. This is ignored by
earlier versions of Terraform, and allows for services using Terraform
modules to be upgraded to the latest Terraform version.
[#182413672](https://www.pivotaltracker.com/story/show/182413672)
> feat: allow upgrade of Terraform modules

- brokerapi/broker/decider/decider.go
- brokerapi/broker/decider/decider_test.go
- brokerapi/broker/update.go
- docs/draft-release-notes.md
- integrationtest/fixtures/terraform-upgrade-updated/fake-service.yml
- integrationtest/fixtures/terraform-upgrade/fake-service.yml
- integrationtest/helper/operations.go
- integrationtest/multiple_update_properties_test.go
- integrationtest/terraform_rename_provider_test.go
- integrationtest/terraform_upgrade_test.go
Once a service instance has been upgraded, Cloud Foundry will put the
service instance's current Maintenance Info into the "previous values"
section of an update request. There's a relatively subtle
differentiation between:
- Downgrading a service instance (where it currently has a maintenance
info version and this is being removed), which is an Upgrade
- Updating a service instance (where there's a previous Maintenance Info
value, and no new Maintenance Info value) where there are other updates
The previous algorithm was hard to reason about, so it has been
redeveloped by adding many more table tests to solidify the behaviour.
As a general rule, Cloud Foundry provides a "previous values" block
which has all the current values, and only provides a new value when it
changes. …
> fix: ability to update after an upgrade

- brokerpaktestframework/broker_pack_path_finder.go
- brokerpaktestframework/osbapi_helper.go
- brokerpaktestframework/terraform_mock.go
- brokerpaktestframework/test_instance.go
- brokerpaktestframework/test_instance_builder.go
- docs/draft-release-notes.md
- integrationtest/brokerpaktestframework_test.go
- integrationtest/fixtures/brokerpaktestframework/fake-service.yml
- integrationtest/fixtures/brokerpaktestframework/manifest.yml
The brokerpaktestframwork failed if a "terraform_upgrade_path" was
specified. This is because the framework used to update the manifest to
have a single version of Terraform at 1.1.4. But when other versions are
specified in the "terraform_upgrade_path" then the manifest validation
fails.
- The brokerpaktestframework now reads the Terraform versions present in
the brokerpak and fakes them all (with the default version)
- There is a test for the brokerpaktestframework which will hopefully
find some of the worst errors in future
- The signature of `FindServicePlanGUIDs()` has been changed to return
an error rather than fail silentlu
- The fake broker is now started on a random port so that it does not
interfere with any locally running CSB instances
- If building the fake brokerpak fails, …
> fix: brokerpaktestframework fails with "terraform_upgrade_path"

- docs/brokerpak-specification.md
- docs/draft-release-notes.md
- pkg/providers/tf/upgrade.go
- pkg/providers/tf/upgrade_test.go
The CSB has been adapted to allow upgrades between Terraform versions when an upgrade path is given. 
It has not been tested or implemented to handle versions of Terraform < 0.12.0. 
For this reason, this change ensures that upgrades attempted on instances using a version of Terraform < 0.12.0 will not be upgraded, and a clear error message is returned. 
[#182491133](https://www.pivotaltracker.com/story/show/182491133)
> feat: upgrades only supported for TF >= 0.12

- docs/draft-release-notes.md
- internal/brokerpak/fetcher/fetch.go
- internal/brokerpak/reader/reader.go
- pkg/brokerpak/config.go
- pkg/brokerpak/registrar.go
The project that this was forked from used to support remote brokerpaks,
and would download them locally before unpacking them. The code for
local brokerpaks appears to have also made a copy of the brokerpak,
which is wasteful of space. Since remote brokerpaks are no longer
supported or functional, this extra copy step has been removed, and will
save on app disk space.
Also the logging of the file walker used to locate brokerpaks has been
removed as this is more commonly annoying and rarely useful
> feat: remove brokerpak duplication with local brokerpak

- docs/draft-release-notes.md
- pkg/providers/tf/provision.go
The command "terraform show" is used in the subsume process, and in
versions of Terraform higher than 0.12 it sometimes has additional
output starting with "Outputs:". This fix removes that additional text so that
subsume continues to function as before.
The need for this kind of fix highlights the fragility of subsume.
[#182571088](https://www.pivotaltracker.com/story/show/182571088)
* ~~[ ] Have you added or updated tests to validate the changed functionality?~~ this is tested in brokerpak integration tests
> fix: handle new "terraform show" output

- docs/draft-release-notes.md
- internal/brokerpak/fetcher/fetch.go
- internal/brokerpak/reader/reader.go
- pkg/brokerpak/config.go
- pkg/brokerpak/registrar.go
This reverts commit 1caba305249371a318822b0990548725bd4b63e3.
@FelisiaM pointed out that remote brokerpaks are still possible to
configure via `brokerpak.sources` in the config file, so someone may
still be using remote brokerpaks.
> feat: revert "feat: remove brokerpak duplication with local brokerpak (#561)"

- internal/brokerpak/reader/reader.go
- pkg/brokerpak/config.go
This is a second attempt at #561 that was reverted in #569
This removes a step that made a copy of a local brokerpak before opening
it.
Also the logging of the file walker used to locate brokerpaks has been
removed as this is more commonly annoying and rarely useful
[#181523458](https://www.pivotaltracker.com/story/show/181523458)
> chore: remove brokerpak duplication with local brokerpak

- internal/brokerpak/manifest/parser.go
- internal/brokerpak/manifest/parser_test.go
A common error is to add a new default Terraform version and fail to
update the terraform_upgrade_path. This adds a check so that if the
terraform_upgrade_path does not terminate at the default version then
the brokerpak will fail to build, resulting in faster feedback.
> fix: checks that terraform_upgrade_path terminates at default version

- brokerapi/broker/update.go
- brokerapi/broker/update_test.go
- integrationtest/fixtures/terraform-upgrade-updated/fake-bind.tf
- integrationtest/fixtures/terraform-upgrade-updated/fake-service.yml
- integrationtest/fixtures/terraform-upgrade/fake-bind.tf
- integrationtest/fixtures/terraform-upgrade/fake-service.yml
- integrationtest/terraform_upgrade_test.go
- pkg/broker/brokerfakes/fake_service_provider.go
- pkg/broker/service_provider.go
- pkg/providers/tf/upgrade.go
- pkg/providers/tf/upgrade_test.go
We observed that the upgrade flow failed when an output property was
added to the service instance. This is because the inputs to binding
were computed before the upgrade had happened, and the value of the new
output was not available. This change splits the upgrade of the service
instance from the upgrade of the service binding, allowing the flow to
work.
There was considerable friction in implementing this because of the
false abstraction of the provider layer from the brokerapi layer. This
abstraction made sense when this repo was a Google project that
supported Terraform and Google API, but it doesn't make sense now, and
should be removed in the near future.
[#182855842](https://www.pivotaltracker.com/story/show/182855842)
* ~~[ ] Have you added Draft Release Notes in …
> fix: upgrade should handle addition of properties

- brokerpaktestframework/test_instance.go
- integrationtest/integrationtest_suite_test.go
- pkg/broker/service_definition.go
- pkg/server/health_test.go
- pkg/toggles/toggle.go
- pkg/validation/field_error.go
There have been some format changes and a change to -gcflags. "gops"
integration was disabled, but it might be easy to re-add it with a
syntax change to the -gcflags argument.
> chore: "go fmt" and fixes for Go 1.19

- brokerapi/broker/bind.go
- brokerapi/broker/broker.go
- brokerapi/broker/provision_test.go
- brokerapi/broker/update_test.go
- pkg/brokerpak/registrar.go
- pkg/featureflags/feature_flags.go
- pkg/providers/tf/deployment_manager.go
- pkg/providers/tf/deployment_manager_test.go
- Adds the DisableRequestPropertyValidation flag to the featureflags
package
- Adds an Enabled() function so that feature flag checking is more
fluent
> chore: tidy up feature flags

- cmd/create_service.go
- internal/brokerpak/packer/pack.go
- internal/createservice/create_service.go
- internal/createservice/nameid.go
This is an experimental new command that mimics the CloudFoundry
"create-service" command, but runs all steps locally. The aim is to
speed up development by allowing for faster iteration when making
changes to brokerpaks.
* ~~[ ] Have you added or updated tests to validate the changed functionality?~~ experimental
* ~~[ ] Have you added Draft Release Notes in `docs/draft-release-notes.md`?~~ experimental
> feat: experimental "create-service" command

- cmd/pak.go
- docs/draft-release-notes.md
- integrationtest/brokerpak_build_test.go
- integrationtest/helper/build_brokerpak.go
- internal/brokerpak/packer/pack.go
- internal/brokerpak/platform/platform.go
- internal/brokerpak/platform/platform_test.go
- internal/createservice/create_service.go
- pkg/brokerpak/cmd.go
- pkg/brokerpak/cmd_test.go
This "--target" flag will override the "platforms" block in the
manifest. It's useful for building for the current platform.
[#181407433](https://www.pivotaltracker.com/story/show/181407433)
> feat(pak): "pak build" --target flag targets specific os/arch or "current"

- Makefile
- internal/brokerpak/packer/cache.go
- internal/brokerpak/packer/pack.go
The previous cache mostly worked but would occasionally be problematic
in areas such as local files, and would occasionally leave out a file.
This change seems to fix that behavior, and also simplifies the code.
> fix: "pak build" caching of files

- brokerpaktestframework/test_instance_builder.go
- cmd/pak.go
- docs/draft-release-notes.md
- internal/brokerpak/packer/pack.go
- internal/brokerpak/reader/reader_test.go
- internal/createservice/create_service.go
- internal/zippy/archive.go
- internal/zippy/archive_test.go
- pkg/brokerpak/cmd.go
- pkg/brokerpak/cmd_test.go
Compressing a brokerpak makes it smaller, but it's hard work for the
processor. During development it can be useful to build brokerpaks
without compression because the speed advantage (it takes less than half
the time to build) outweighs the size advantage.
> feat: "pak build" --compress option to disable compression

- brokerapi/broker/update.go
- brokerapi/broker/update_test.go
After executing a `deprovision` operation whose result was not satisfactory, the type of the last operation performed in the instance was stored in the database, that is, OperationType = deprovision, as established by the business logic. If after the `deprovision` operation, we performed an operation of updating a property of the same instance, for example modifying the property `deletion_protection` in some of the database services of some of the providers, the type of the last operation performed in the instance was not stored, that is, we did not assign the value `update` to the type of the last operation performed in the instance.
After a new call to endpoint /v2/service_instances/:instance_id/last_operation due to an asynchronous operation, the logic associated with this endpoint …
> fix: set operation type in instance when updating

- pkg/varcontext/interpolation/assets/example-config.yml
- pkg/varcontext/interpolation/eval_test.go
- pkg/varcontext/interpolation/funcs.go
if the broker uses a brokerpak that in turn uses
`${config("yaml.path.to.item")} HIL funtion, configs can only be parsed when the yaml value for `yaml.path.to.item` is a string. e.g.:
this will work
```
yaml.path.to.item: '{"key":"value"}'
```
this wont:
```
yaml.path.to.item: {"key":"value"}
```
this neither
```
yaml.path.to.item:
key: value
```
we should support passing in valid yaml and json configuration via config files for items referenced via the hil func config.
* ~[ ] Have you added Release Notes in the docs repositories?~
> fix: make config parsing sane

- internal/testdrive/broker_create_binding.go
- internal/testdrive/broker_delete_binding.go
- internal/testdrive/broker_deprovision.go
- internal/testdrive/broker_last_operation.go
- internal/testdrive/broker_provision.go
- internal/testdrive/broker_update.go
- internal/testdrive/broker_upgrade.go
- internal/testdrive/error.go
By returning custom errors, it's possible to match against status code and body, rather than relying on string matching of the rendered error.
[#183405838](https://www.pivotaltracker.com/story/show/183405838)
> test: testdrive should return matchable errors

- brokerapi/broker/bind_test.go
- brokerapi/broker/deprovision_test.go
- brokerapi/broker/last_instance_operation_test.go
- brokerapi/broker/provision_test.go
- brokerapi/broker/unbind.go
- brokerapi/broker/unbind_test.go
- integrationtest/fixtures/osbapi/fake-provision.tf
- integrationtest/fixtures/osbapi/fake-service.yml
- integrationtest/fixtures/osbapi/manifest.yml
- integrationtest/osbapi_test.go
The Open Service Broker API (OSBAPI) spec says that an HTTP 410 should be returned when trying to delete a binding that does not exist.
[#183405838](https://www.pivotaltracker.com/story/show/183405838)
> fix: return HTTP 410 when deleting non-existent binding

- internal/testdrive/broker.go
When the broker fails to start in a test (often an error that we are in the process of testing), we occasionally get a panic from the test framework.
> test: failures to start the broker should not cause panic

- dbservice/dbservice.go
- internal/local/store.go
If the "csb services" command was run with an empty DB, it failed because the database tables had not been created yet. They are now created after the first DB connection.
> fix: dev command "csb services" should succeed with emtpty DB

- README.md
- cmd/local.go
- internal/local/list_examples.go
- internal/local/run_examples.go
Previously, to run the example tests, one had to start a broker in one terminal, and run the "csb client run-examples" command in another terminal. This feature builds on the CSB local experience and automatically starts the broker for you. The new commands are:
- csb examples (to list examples)
- csb run-examples (to run examples)
This feature is experimental for now, and the old functionality still exists. Assuming the new way works well, we should eventually remove the old way.
> feat: example tests automatically start broker

- pkg/client/example_runner.go
The very latest staticcheck picks up on some more deprecation warnings, and this change fixes the warnings.
> chore: remove usage of deprecated constants

- cmd/serve.go
- integrationtest/no_services_test.go
From time to time, someone misconfigures the broker so that no services are defined. When this happens, the broker starts successfully but when registering to CloudFoundry the "cf create-service-broker" command fails. Often folks spend a lot of time investigating CloudFoundry, when an earlier failure would have directed them to the source of the problem. This commit introduces the earlier failure by refusing to start when no services are defined.
> fix: broker should not start when no services are definied

- cmd/serve.go
- go.mod
- pkg/server/docs.go
- pkg/server/health.go
- pkg/server/health_test.go
The gorilla/mux project has been archived which means that we can't rely on receiving security fixes in the future. The brokerapi package is tightly integrated with gorilla/mux, but the cloud-service-broker code only uses it as a convenience. This commit removes direct usage of gorilla/mux, but the project still uses it indirectly via brokerapi.
[#184006000](https://www.pivotaltracker.com/story/show/184006000)
> chore: remove direct usage of gorilla/mux

- go.mod
- go.sum
We have seen issues in tests using SQLite where the database becomes locked. As a first attempt at a fix, it makes sense to update to the latest version of the driver.
> chore: update gorm.io/driver/sqlite

- dbservice/setup_db.go
SQLite3 does not support performing similar operations (e.g. INSERT) concurrently on the same table from the same connection. As CSB uses the same database connection for all goroutines, we were occasionally seeing errors saying "database is locked".
Enabling the full mutex mode will serialise database operations and hopefully stop this error from occurring.
> fix: SQLite3 concurrency issues when running examples

- pkg/providers/tf/workspace/module.go
CodeQL go/missing-error-check is being activated because `diags.HasErrors()` is being used instead of the standard nil check. Adding an explicit nil check to silence the error, without changing behaviour.
> chore: silence CodeQL linting warning

- internal/brokerpak/packer/cache.go
When using a cache to build brokerpaks, a source path is converted into an MD5 sum and this is used to name a directory in the cache, which is populated by the contents. It was observed that cache directories were sometimes empty - presumably because the operating system was cleaning up files in /tmp. But because the cache directory still existed, it was still considered valid, and a brokerpak would be successfully built, but with missing content. This commit introduces an additional check that the cache directory should not be empty, which should resolve this kind of error.
> fix: invalid cache state causing invalid brokerpaks

- internal/brokerpak/reader/reader_test.go
- pkg/brokerpak/cmd.go
- pkg/brokerpak/cmd_test.go
- pkg/brokerpak/registrar_test.go
- pkg/providers/tf/definition.go
Previously, the newly created brokerpak had `00000000-0000-0000-0000-000000000000` as the service GUID, and
`00000000-0000-0000-0000-000000000001` as the plan GUID. This would require the author to re-generate the above values. The probability of GUIDs clashing in this case is negligible.
* [~] Have you added or updated tests to validate the changed functionality?
* [~] Have you added Release Notes in the docs repositories?
> feat: `pak init` to include usable GUIDs in the template

- pkg/featureflags/feature_flags.go
- pkg/providers/tf/invoker/terraform_invoker_factory.go
- pkg/providers/tf/invoker/terraform_invoker_factory_test.go
> feat: remove CSB_DISABLE_TF_UPGRADE_PROVIDER_RENAMES feature flag

- Dockerfile
Pins the version of Alpine in the Dockerfile to avoid an issue where the latest Alpine does not work with sqllite.
[#186660285](https://www.pivotaltracker.com/story/show/186660285)
> chore: pin Dockerfile Alpine version

- .github/workflows/codeql.yml
- go.mod
Related PRs:
- https://github.com/argentumcode/systemd-failure-pagerduty/pull/8/files
- https://github.com/cloudfoundry/cloud-service-broker/pull/947
- https://github.com/cloudfoundry/cloud-service-broker/pull/948
> chore: make codeql action use golang specified in go.mod

- Makefile
- docs/user-guides/developer-experience.md
[#187027977](https://www.pivotaltracker.com/story/show/187027977)
Before Go 1.21:
- The go directive was advisory only; now it is a mandatory requirement
- The go directive didn't allow specifying patch versions
So, by specifying the patch version in go.mod:
- Noone can unknowingly test, run or build this project using an older version of go
- The required Go toolchain can be downloaded automatically
Therefore, checking the current go version in Makefile is no longer needed.
> chore: stop checking go version in Makefile

- integrationtest/binding_cleanup_test.go
- integrationtest/fixtures/binding-cleanup/fake-bad-bind.tf
- integrationtest/fixtures/binding-cleanup/fake-bad-service.yml
- integrationtest/fixtures/binding-cleanup/fake-good-bind.tf
- integrationtest/fixtures/binding-cleanup/fake-good-service.yml
- integrationtest/fixtures/binding-cleanup/fake-provision.tf
- integrationtest/fixtures/binding-cleanup/manifest.yml
- integrationtest/fixtures/provision-cleanup/fake-string-provision.tf
- integrationtest/fixtures/provision-cleanup/fake-string-service.yml
- integrationtest/fixtures/provision-cleanup/manifest.yml
- integrationtest/provision_cleanup_test.go
- internal/testdrive/broker_create_binding.go
- internal/testdrive/broker_provision.go
We have an issue where we fail to clean up if there is an issue with the Terraform state. Here we introduce some tests that capture that behaviour. By reproducing the error in a test, we can test-drive a solution and have better confidence that we have fixed the issue.
[#185835561](https://www.pivotaltracker.com/story/show/185835561)
> test: reproduce failed cleanups

- cmd/purge.go
- cmd/purge_binding.go
- integrationtest/fixtures/purge-service-binding/fake-service.yml
- integrationtest/fixtures/purge-service-binding/manifest.yml
- integrationtest/purge_service_binding_test.go
The CSB command has a "purge" subcommand for purging a whole service instance. This adds a "purge-binding" subcommand for purging just a single binding.
[#185835561](https://www.pivotaltracker.com/story/show/185835561)
> feat: ability to purge a service binding

- Dockerfile
[#187010312](https://www.pivotaltracker.com/story/show/187010312)
> chore: pin golang image to latest

- brokerapi/broker/deprovision.go
- brokerapi/broker/deprovision_test.go
- brokerapi/broker/unbind.go
- brokerapi/broker/unbind_test.go
- integrationtest/binding_cleanup_test.go
- integrationtest/provision_cleanup_test.go
- internal/testdrive/broker_deprovision.go
- pkg/providers/tf/workspace/cannot_read_version_error.go
- pkg/providers/tf/workspace/workspace.go
- pkg/providers/tf/workspace/workspace_test.go
NOTE: please merge PR #954 first
As part of the upgrade epic, we added checks to make sure that service
instances and bindings had been updated to the latest version. This
involves parsing the Terraform state and extracting the version. But
sometimes the Terraform state is not valid due to being empty, or being
invalid JSON. Typically this is after a failure to provision/bind,
and the service instance or binding is in a failed state. In these
situations, the lack of state data means CSB does not have enough data to
successfully clean up using Terraform. We have had feedback that this
can be problematic for users because they have to do a manual purge of
the service instance, and it would be easier if the delete operations
would just work. This is a tradeoff because a manual purge could …
> fix: successfully delete instances and bindings with invalid state

- cmd/config.go
- cmd/local.go
- cmd/pak.go
- cmd/purge.go
- cmd/purge_binding.go
- cmd/root.go
- cmd/serve.go
- cmd/tf.go
- cmd/version.go
> chore: improve help command output

- dbservice/dbservice.go
- dbservice/recover_in_progress_operations.go
- dbservice/recover_in_progress_operations_test.go
- integrationtest/termination_recovery_test.go
- previously if an operation was in progress when the broker terminated it would forever be recorded as "in progress" in the broker database and was hard to clean up
- now on startup, the broker marks any in-progress operations as failed
- this allows the service instance to be cleaned up without intervention from a CloudFoundry administrator
[#178142867](https://www.pivotaltracker.com/story/show/178142867)
> fix: recover in-progress operations on broker restart

- cmd/tf.go
- pkg/providers/tf/definition.go
- pkg/providers/tf/deployment_manager.go
- pkg/providers/tf/deployment_manager_test.go
When doing a provision/update/delete/../etc operation, if it fails for any reason, we update last operation status and message. However we only return an error from the last_operation endpoing under the certain circumpstances (see [OSBAPI spec](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#polling-last-operation-for-service-instances). All other circumpstances the return code is OK and we only log the operation status (failed), but not the message (brokerapi does this for us).
With that into consideration, we need to log any error messages that ocurr in our application to improve troubleshooting. This change logs the error message that will be saved into the last operation message whenever last operation is updated with a failed state. …
> feat: log the error message when an async operation fails

- cmd/serve.go
- dbservice/dbservice.go
- dbservice/dbservice_suite_test.go
- integrationtest/tf_dump_test.go
An error was discovered where database startup, including database migrations and failed operation recovery was being run for every command that accessed the database, including "tf dump". This had the effect of marking any in-progress operations as failed, even if they were still really in progress. This has been a problem since the introduction of in-progress operation recovery in v1.1.0 (commit c8452677ef3d141efd150c5adbd4392377e2439c).
[#187500102](https://www.pivotaltracker.com/story/show/187500102)
> fix: only run database startup when running server

- pkg/server/cf_sharing.go
This allows "go generate ./..." to succeed
> test: update path for generated fake

- docs/configuration.md
- pkg/broker/registry.go
- pkg/broker/registry_test.go
- pkg/broker/service_definition.go
The "enable-builtin-services" feature toggle enabled the GCP API services in the original Google Service Broker. These were removed long ago in the Cloud Service Broker, and this config flag does nothing.
> chore: remove unused "builtin" feature toggle

- brokerpaktestframework/test_instance.go
- cmd/client.go
- go.mod
- integrationtest/integrationtest_suite_test.go
- integrationtest/subsume_test.go
- integrationtest/termination_recovery_test.go
- internal/local/catalog.go
- internal/testdrive/broker_create_binding.go
- internal/testdrive/broker_delete_binding.go
- internal/testdrive/broker_deprovision.go
- internal/testdrive/broker_last_operation.go
- internal/testdrive/broker_provision.go
- internal/testdrive/broker_start.go
- internal/testdrive/broker_update.go
- internal/testdrive/broker_upgrade.go
- pkg/brokerpak/cmd.go
- pkg/client/example_runner.go
[#187659119](https://www.pivotaltracker.com/story/show/187659119)
> chore: replace unmaintained uuid library

- pkg/broker/service_definition.go
- pkg/broker/service_definition_test.go
encrypted_passwords
plan definitions
provision defaults and other overrides in services currently csb expects
service.something.plans to be a STRING. The code will do some manual deserializing and would fail if that path in the yaml / json config didn't contain a string.
This adds support for using real json / yaml objects to configure the csb app. In the current deployment process of csb via a Tile, multiple layers of config are rendered and ensuring that (e.g. plans) value stays a string is convoluted and error prone. We should just allow using actual objects instead of expecting string representations of objects..
add comments for helper functions to access viper config
[#187498188]
> feat: allow yaml / json objects in config files for

- docs/brokerpak-specification.md
- internal/brokerpak/manifest/parser_test.go
- internal/brokerpak/platform/platform.go
Add validation for Platform Object.
- Allow only values which are valid for `$GOOS` and `$GOARCH` (required for `func CurrentPlatform()` to work)
- Allow only values for which there is an OpenTofu release (required to download binaries, see `brokerpakurl.go`) 
Update Brokerpak specification to list correct values for allowed OS and Arch
> feat: add validation for allowed OS and Arch combinations

- brokerapi/broker/deprovision.go
- brokerapi/broker/deprovision_test.go
We had code to handle a sync deprovision, but the CSB cannot do a sync deprovision, so it's code that could never be run.
> chore: remove unused code for sync deprovision

- brokerapi/broker/last_instance_operation.go
- brokerapi/broker/last_instance_operation_test.go
We now differentiate between an instance not existing, and having an error getting the record from the database. All the other endpoints did this, so this just gets LastOperation to follow the same pattern
> chore: report database error during LastOperation

- dbservice/migrations.go
- dbservice/models/historical_db.go
- internal/storage/service_instance_details.go
- internal/storage/service_instance_details_test.go
These fields are not used in the codebase, so we should get rid of them.
Because this follows on fast from https://github.com/cloudfoundry/cloud-service-broker/commit/eabd3d631efb9c27ceb763456a06f67c99016ca1, I've updated the migration in that commit rather than add a new migration. As long as they both go out in the same release, then no-one will be exposed to the intermediate state.
> chore: drop unused Location and URL database fields

- pkg/providers/tf/deployment_manager_test.go
These are some changes to tests that when merged with PR #1102 will hopefully allow the tests to continue working.
> test: updates to allow #1102 to be merged

- dbservice/vcap.go
- dbservice/vcap_test.go
The for loop on L103 was written to return after the checking the first entry in vcapMap, regardless of whether findMySQLTag found a suitable service or returned an error. If services from multiple service offerings are bound to the application and the service tagged with "mysql" is not in the first offering, the function will not find it. The new test case fails when run against the unmodified code.
To fix this, flatten the map[string][]VcapService into a []VCapService, and pass the flat slice to findMySQLTag.
> fix: ParseVcapServices stops searching after the first service offering

- pkg/providers/tf/bind_test.go
- pkg/providers/tf/deployment_manager_test.go
- pkg/providers/tf/provision_test.go
- pkg/providers/tf/workspace/workspace.go
- pkg/providers/tf/workspace/workspace_test.go
Func NewWorkspace returns proper go zero-values for each function parameter that is empty. 
This PR fixes unintended changes in the behavior of func NewWorkspace due to #1102 and causes the function to keep the principle of least confusion:
- #1102 changed the values which are returned in case the function parameters `terraformTemplates`, `importParameterMappings`, `parametersToRemove` and `parametersToAdd` are empty. This PR reverts this behaviour and keeps backwards-compability
- fixes failed tests in #1102 
- reverts #1114
> refactor: func NewWorkspace returns proper zero-values for empty function parameters

- docs/configuration.md
- pkg/config/config.go
- pkg/credstore/credstore.go
- pkg/credstore/credstore_test.go
The Credhub `ca_cert_file` was not being generated during installation. Instead, the Ops Manager certificate was being included in an unexpected configuration key.
Previously, the broker app ran on Diego and utilized the Cloud Foundry certificate trust store (the Ops Manager CA certificate was located in the container’s /etc/cf-system-certificates path).
Now, the broker runs on its own VM without automatic injection of the Ops Manager root CA or CF trust store. Although ca_cert was present in the job configuration, the broker wasn’t utilizing it, leading to the following error: `tls: failed to verify certificate: x509: certificate signed by unknown authority.`
> fix: use ca_cert instead of ca_cert_file

- integrationtest/fixtures/terraform-upgrade-failure-updated/fake-bind.tf
- integrationtest/fixtures/terraform-upgrade-failure-updated/fake-provision.tf
- integrationtest/fixtures/terraform-upgrade-failure-updated/fake-service.yml
- integrationtest/fixtures/terraform-upgrade-failure-updated/manifest.yml
- integrationtest/fixtures/terraform-upgrade-failure/fake-bind.tf
- integrationtest/fixtures/terraform-upgrade-failure/fake-provision.tf
- integrationtest/fixtures/terraform-upgrade-failure/fake-service.yml
- integrationtest/fixtures/terraform-upgrade-failure/manifest.yml
- integrationtest/terraform_upgrade_failure_test.go
- pkg/providers/tf/upgrade.go
- pkg/providers/tf/upgrade_test.go
Previously when an upgrade stage failed, we recorded the new (higher)
TF version in the state anyway, so if the upgrade were retried, it
would be skipped because it was already deemed to be at this version.
Now we first do an upgrade/apply at the current version to account for
potentially failed upgrades. For successful upgrades this should be a
no-op as TF is idempotent, and it's cleaner to use idempotency rather than
keep track of success/failure ourselves.
> fix: allow failed upgrade to be re-tried

- pkg/client/example_runner.go
Getting lint check: non-constant format string in call to fmt.Errorf
errors.New() is a better way to write this
> chore: resolve lint check

- .github/workflows/focused-test.yml
- Makefile
- go.mod
- tools/tools.go
https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.87.0 is incompatible with 1.24
Until a version is released that fixes 1.24 compatibility issues, cloud-service-broker will use 1.23.6.
This reverts changes to make use of 1.24 features.
> chore: Revert go 1 24 features

- pkg/config/config.go
- pkg/credstore/credstore_test.go
The property can be read in from the environment, but it's never used in the code so has no effect.
> chore: removed unused config property CH_STORE_BIND_CREDENTIALS

- .github/workflows/mlc-config.json
For one particular link that results in a GitHub search we are consistently getting HTTP 429 (too many requests) when checking the link in CI, but it works perfectly when run outside of CI. Our assumption is that it's rate limiting by GitHub - probably due to all the other jobs running on the same GitHub Actions worker. If we skip that particular link, we can still check the others.
> chore: fix Markdown lint check

- internal/paramparser/parse_bind_details.go
- internal/paramparser/parse_bind_details_test.go
This is provided by CF when there is no app guid
> chore: ability to parse credential_client_id from binding details

- internal/paramparser/parse_bind_details.go
- internal/paramparser/parse_bind_details_test.go
- pkg/broker/service_definition.go
In OSBAPI, the "app_guid" field in the request has been deprecated in favour of "bind_resource.app_guid". We have been treating these as separate GUIDs when in fact they are the same thing appearing in different locations.
> chore: binding has only one App GUID

- docs/configuration.md
- internal/local/environment.go
- utils/utils.go
Exposes and documents the CSB_LOG_LEVEL environment variable to allow the Lager log level to be set.
> chore: allow log level to be set via CSB_LOG_LEVEL
